from tkinter import *
def inputs():
    f=open("7h_hw.txt","a")
    f.write(f"The Name of the User is {name.get()}\nThe age of the user is {age.get()}\n")
    print("Enter credentials of next member")
    #print(f"The Name of the User is {name.get()}")
    #print(f"The age of the user is {age.get()}")
root=Tk()
root.geometry("555x555")
f1=Frame(root,bg="grey")
f1.pack(side=TOP)
lbl=Label(f1,text="WELCOME TO DANCE CLASS",font="comicsansms 19 bold",bg="blue",fg="yellow")
lbl.pack()
f2=Frame(root)
f2.pack(side=TOP,anchor="nw")
user=Label(f2,text="Name")
agee=Label(f2,text="Age")
user.grid()
agee.grid(row=1)
name=StringVar()
age=IntVar()
name_entry=Entry(f2,text=name)
age_entry=Entry(f2,text=age)
name_entry.grid(row=0,column=1)
age_entry.grid(row=1,column=1)
Button(f2,text="Submit",command=inputs).grid(row=2,column=1)
root.mainloop()